### ISSUE TITLE
Ability to get the resource update article / changelog

### ISSUE THREAD

**Issue by DrOreo002** [SpigotMC/XenforoResourceManagerAPI#14]
Would be great if I can get the update article of my resources, so then I can make a discord bot that will announce the update + the change log at the same time without me writing it by my own at my discord channel

**Comment by simpleauthority** [comment]
You want the post content? What about a truncated version?

**Comment by DrOreo002** [comment]
> You want the post content? What about a truncated version?

Full article content would be nice

**Comment by simpleauthority** [comment]
sorry for the wait, coming next pr
