### ISSUE TITLE
Get latest profile post by user

### ISSUE THREAD

**Issue by LagBug** [SpigotMC/XenforoResourceManagerAPI#16]
Hi there,

It would be really nice to see **getAuthor** also return the latest profile post by the specified user. By doing that, verification bots for Discord could easily link discord users with their equivalent spigot account.

**Comment by LagBug** [comment]
EDIT: Just saw the closed issues made before me. Why aren't we allowed to use the API for verification?   Also, an "identities PR" is mentioned, what's that exactly?

**Comment by MiniDigger** [comment]
see https://api.spigotmc.org/simple/0.1/index.php?action=getAuthor&id=6039

the author response has an identities field, those are set here https://www.spigotmc.org/account/contact-details

so just let ppl fill in their discord name there

**Comment by LagBug** [comment]
Oh alright, that'll do. Thanks.
