### ISSUE TITLE
getAuthor for users without resources returns 404

### ISSUE THREAD

**Issue by MiniDigger** [SpigotMC/XenforoResourceManagerAPI#17]
I am not sure if this is a bug or just not possible (this is the resource manager api after all), but its currently impossible to use this for verification properly, as its only returns responces for ppl that have resources

for example, andrewkm has no resources, as such this endpoint returns a 404
https://api.spigotmc.org/simple/0.1/index.php?action=getAuthor&id=2

**Comment by darbyjack** [comment]
The reason this is throwing that error is that, in the latest push, any authors without identities return a 404. It is being looked into and investigated.

**Comment by simpleauthority** [comment]
I'll check this soon.
