### ISSUE TITLE
Add icon URL to getResource option

### ISSUE THREAD

**Issue by Andre601** [SpigotMC/XenforoResourceManagerAPI#22]
The `getResource` option should have an additional value, where the Icon URL of the resource is provided.
This could/should perhaps return the URL for the default resource icon, if none is set.

**Comment by simpleauthority** [comment]
Please see #15

**Comment by Andre601** [comment]
I see.

But the issue I would face now is, that there's no validation of if the resource actually does have a icon set, or if it is the default one, so the solution you suggested is only semi-optimal.

**Comment by robertlit** [comment]
> Also, you provide an example with a method (`floor(id/1000)`) that wouldn't even work as it probably should (requires double but you give int)


You can use `id / 1000` without `floor()`, since, as you said, the value is already an integer.

**Comment by Andre601** [comment]
The issue persist tho, that you can't use this method on resources that don't have an icon set, as the default icon is a specific URL, that doesn't change and isn't dynamic unlike the resource's icon.

**Comment by robertlit** [comment]
If a resource has no icon, you will get a 404. You can check if the response code is 404, and if it is, use the default (static) image url.

**Comment by Andre601** [comment]
> If a resource has no icon, you will get a 404. You can check if the response code is 404, and if it is, use the default (static) image url.

Still requires me to do a separate request just to check if the URL is valid, which is quite pointless to do.
What is so wrong about just returning an icon field that has either a String or null?

**Comment by simpleauthority** [comment]
We can add such a field, but it will take time. I currently do not have access to a development instance of XF (was using a friend's before, but it is not available). I will need to buy XF to add this feature. I do apologize. I have no ETA.

**Comment by md-5** [comment]
>The issue persist tho, that you can't use this method on resources that don't have an icon set, as the default icon is a specific URL, that doesn't change and isn't dynamic unlike the resource's icon.

The default icon is based on the user's forum theme, it shouldn't be part of the API

**Comment by Andre601** [comment]
> > The issue persist tho, that you can't use this method on resources that don't have an icon set, as the default icon is a specific URL, that doesn't change and isn't dynamic unlike the resource's icon.
> 
> The default icon is based on the user's forum theme, it shouldn't be part of the API

How is it based on the user's theme? From the 9 themes I have access to does none havy any other default icon. It was always https://static.spigotmc.org/styles/spigot/xenresource/resource_icon.png, so this is basically just nothing more than an excuse imo.

It really can't be THAT difficult to have the iconUrl (or parts of it) be returned or an empty string/null when no custom icon was set.
This would it make easy for us to just do something like `if(iconUrl.isEmpty()) iconUrl = "https://static.spigotmc.org/styles/spigot/xenresource/resource_icon.png";` for that case.

Again, none of the themes that I (a donator) have access to has an other link to the default icon used in a resource.

**Comment by simpleauthority** [comment]
done, next pr

sorry for the wait
