### ISSUE TITLE
Suggestion: add a search option

### ISSUE THREAD

**Issue by Olzie-12** [SpigotMC/XenforoResourceManagerAPI#24]
Add search option to get an array of the users that have that name

**Comment by simpleauthority** [comment]
Names are unique on Spigot. How would this work?

**Comment by MiniDigger** [comment]
smth like `.*simple.*` prolly?

**Comment by Olzie-12** [comment]
Ah, okay just return a author that has that name

**Comment by simpleauthority** [comment]
Not sure why this was closed. We are working on it, but it may not be in the timeframe you desire. Please exercise patience. Closing out of annoyance only serves to create more annoyance.

**Comment by Olzie-12** [comment]
> Not sure why this was closed. We are working on it, but it may not be in the timeframe you desire. Please exercise patience. Closing out of annoyance only serves to create more annoyance.

Haha sorry, my bad

**Comment by Olzie-12** [comment]
> will be in the next pr

thank you
