### ISSUE TITLE
Make getAuthor return purchased resources

### ISSUE THREAD

**Issue by LagBug** [SpigotMC/XenforoResourceManagerAPI#25]
So, I was thinking, instead of #8 which would require more work and seems to be harder to implement, the getAuthor method could return the IDs of the purchased resources of the user. I think this would be a really good way for authors to verify real buyers I don't know whether some people will consider it a privacy issue.

**Comment by MiniDigger** [comment]
Yeah, I don't think it's a good idea to do that, lol.
What resources somebody brought shouldn't be public.
