### ISSUE TITLE
Requests blocked

### ISSUE THREAD

**Issue by InventivetalentDev** [SpigotMC/XenforoResourceManagerAPI#26]
Hey!
Just noticed Spiget seems to be blocked from the API and receives 1020 CloudFlare errors as of recently.  
Was wondering if you had some insight as to why that's happening?

**Comment by simpleauthority** [comment]
Unfortunately I have no idea... I don't have control over where it's hosted. @md-5 would be the one to reach out to. I've pinged him here.

**Comment by md-5** [comment]
There’s definitely no blocking on the api.spigotmc.org domain

As for the forums: https://www.spigotmc.org/threads/official-support-faqs.311785/#post-3758230

**Comment by InventivetalentDev** [comment]
Was an issue on my end that only popped up a couple of days ago, sorry!
