### ISSUE TITLE
Get the latest spigot download version/getting the download link

### ISSUE THREAD

**Issue by Olzie-12** [SpigotMC/XenforoResourceManagerAPI#28]
This would be lovely to add, as you can simply make a lot of automatic downloads for loads of resources. This would be so beneficial.

**Comment by MiniDigger** [comment]
duplicated of #7

**Comment by Olzie-12** [comment]
Do you know when it’s going to be introduced?

**Comment by simpleauthority** [comment]
@Olzie-12 please continue discussion and provide a +1 and rationale of your intended use over at #7 

thank you
