### ISSUE TITLE
Identities returning wrong keys

### ISSUE THREAD

**Issue by LaxWasHere** [SpigotMC/XenforoResourceManagerAPI#30]
![](https://i.imgur.com/QFaxxP7.png)

Discord key is now facebook
yahoo key returned twitter

https://api.spigotmc.org/simple/0.1/index.php?action=getAuthor&id=106

**Comment by simpleauthority** [comment]
More database weirdness! Woot!

**Comment by MrIvanPlays** [comment]
This isn't even consistent... discord for me returns gtalk
![image](https://img.mrivanplays.com/LpVASMn67a.png)
https://api.spigotmc.org/simple/0.1/index.php?action=getAuthor&id=209496 :eyes:

**Comment by simpleauthority** [comment]
> This isn't even consistent... discord for me returns gtalk
> ![image](https://camo.githubusercontent.com/a5e27465dbf433ec9bf8d8bde842fdc77bdbe969/68747470733a2f2f696d672e6d726976616e706c6179732e636f6d2f4c705641534d6e3637612e706e67)
> https://api.spigotmc.org/simple/0.1/index.php?action=getAuthor&id=209496 👀

Yeah there is a difference between my database where I develop this and Spigot's DB where it is deployed. I'm trying to think of a proper solution.

**Comment by simpleauthority** [comment]
I think I have a fix, will need to deploy to know for sure due to differences between dev and prod env. Next pr.
