### ISSUE TITLE
Add supported versions

### ISSUE THREAD

**Issue by Andre601** [SpigotMC/XenforoResourceManagerAPI#31]
It would be useful, if the `getResource` action would also return the "Tested Minecraft versions" output from a resource (Maybe either as a JSON array or as a comma-separated String)

It could perhaps be called something like `mc_versions`.

**Comment by simpleauthority** [comment]
Need to get some info from @md-5 before I can do it. PMed him.

**Comment by simpleauthority** [comment]
Will be in next pr
