### ISSUE TITLE
Endpoint to get resource list

### ISSUE THREAD

**Issue by Phoenix616** [SpigotMC/XenforoResourceManagerAPI#32]
It would be cool to have an endpoint similar to getResourcesByAuthor (maybe getResources) which returned a similar list as the author endpoint with all available resources (like the normal [resource listing](https://www.spigotmc.org/resources/) on the page does). It should include a parameter to specify the ordering as well as filtering for the category that gets displayed. (Edited to include all resources and have categories/sorting via parameter)

This would need some kind of pagination though as the list of resources would obviously be a lot longer than the author list and should probably not be all returned in one array.

**Comment by robertlit** [comment]
I don't see many use cases where you'd need to get 1000+ resources.
The category of a resource could be added to the response of the existing endpoints, though.

**Comment by Phoenix616** [comment]
Could be used for statistical stuff and better searching. I'd rather not rely on third party scripts/apis for stuff if the option exists to have an official way to get the info ;)

**Comment by simpleauthority** [comment]
What's the actual programmatic use-case? You should remember that the API results are cached for 6 hours, so I have no idea how it would contribute to better searching. It's not meant to be interfaced with directly by a human (or by a (web || *) app that a human is using) to replace the default UI in the forum which is the only use-case I can imagine.

If you have a different one, please share.

**Comment by Phoenix616** [comment]
The main use case that I envisioned which would need such an api would be of analytical nature, like tracking of the activity/performance/ratings of lots of resources/in certain categories or maybe even finding trending categories/resources based on download counts.

**Comment by Phoenix616** [comment]
Changed this issue to include listing all resources to be able to have complete access to the data provided by the [site's listing](https://www.spigotmc.org/resources/) without having to query each category. (Categories should just be parameters)

Also this listing should include the ability to sort it like it's possible on the site itself.

**Comment by simpleauthority** [comment]
This has been addressed in the next PR, sorry for the wait
