### ISSUE TITLE
Link Java wrapper in readme

### ISSUE THREAD

**Issue by robertlit** [SpigotMC/XenforoResourceManagerAPI#33]
I made a Java wrapper of this API,
I believe it fully wraps the functionality that the API currently offers.
It can be found here: https://github.com/robertlit/SpigotResourcesAPI/
I think linking it in the readme could help some people.

**Comment by simpleauthority** [comment]
It's not officially supported by the project, so we can't do that as then we would be expected to support it as well. I would talk to @md-5 about making it parented by SpigotMC. If so, then sure. But as of now we can't do that.
