### ISSUE TITLE
API Missing Important Information

### ISSUE THREAD

**Issue by Vagdedes** [SpigotMC/XenforoResourceManagerAPI#35]
When you visit a plugin's overview page, you are able to see the "total" amount of reviews in the small selection tab (https://prnt.sc/uwx8tk) and the "unique" amount of reviews in the information box (https://prnt.sc/uwx9cu). However, the API only returns the "total" amount of reviews only, which after a quick conversation with a SpigotMC resource staff member, we established this doesn't make sense, and I was instructed to open an issue about this here. If possible, please add the ability to retrieve this data.

**Comment by simpleauthority** [comment]
I don't understand what change is being requested. Can you show an example in the API response data and what needs to change please

**Comment by Vagdedes** [comment]
Apologies for making this too abstract. 

For example, the API (https://api.spigotmc.org/simple/0.1/index.php?action=getResource&id=25638) will return stats->reviews as 477 (https://prnt.sc/uz7sbi), which is the "total" amount of reviews, and there's nothing wrong with that. However, if we visit the resource and read its information box (https://prnt.sc/uz7okk), it mentions 335, the amount of "unique" reviews. 

In essence, a user can post a review per resource update. There's a total of 335 users that have reviewed the resource and a total of 477 reviews available, because some users have posted more than 1 review over time. The users-reviewed, unique-reviews or however you wish to name it is not retrievable information by the API, and that's what I am requesting to be added.

I hope this makes more sense :D

**Comment by simpleauthority** [comment]
sorry for the wait, coming in the next pr
