### ISSUE TITLE
Identities privacy settings are discarded

### ISSUE THREAD

**Issue by robertlit** [SpigotMC/XenforoResourceManagerAPI#36]
In the privacy settings on the forums there is an option to choose who can view your identities. This option is discarded when accessing information through this API as one can perform the ```getAuthor``` action and view user's identities that one can't view on the forums.

Identities should be exposed via this API only if a user has set them visible to the public.

**Comment by robertlit** [comment]
Forgot to mention, there are two options that should be accounted for: ```People who may view your details on your profile page``` and ```People who may view your identities```.

**Comment by simpleauthority** [comment]
We'll account for `People who may view your identities` but not `People who may view your details on your profile page`.

The data returned is public and not PII regardless of profile privacy (username, resource count, anonymized avatar information).

If `People who may view your identities` is not everyone, then identities will be omitted entirely from the response data which should be sufficient.

Will be in next pr.
