### ISSUE TITLE
Include external download URL in resource information


### ISSUE THREAD

**Issue by Phoenix616** [SpigotMC/XenforoResourceManagerAPI#39]
It would be nice if the resource endpoints could include a field for the latest external download URL if that is set.

The thinking behind this is that downloading from Spigot directly via the api will most likely not happen for various reasons (see #7) so being able to at least access external downloads and then let them handle whether or not they want automatic downloads would be the next best option imo..

Currently that information is only accessible via the redirect of the download button link which of course is locked behind cloudflare. :S

**Comment by bolandnick18** [comment]
Please add this?

**Comment by MrIvanPlays** [comment]
there are various ways to bypass cloudflare and get the html code of the resource page, then use a reader and get the download link, but you can never get it to properly download.
thats why i targeted downloading a resource's version rather than getting a download link.
