### ISSUE TITLE
Ability To Verify Discord

### ISSUE THREAD

**Issue by PeachesMLG** [SpigotMC/XenforoResourceManagerAPI#40]
Ik CabeBabe has a verification tool where you can link your spigot account to discord, would be cool if there was some sort of api so that we can implement that on our custom bots.
Not sure if this is outside the scope of this or not but I thought id post it here see what you guys think

**Comment by simpleauthority** [comment]
> 
> 
> Ik CabeBabe has a verification tool where you can link your spigot account to discord, would be cool if there was some sort of api so that we can implement that on our custom bots.
> Not sure if this is outside the scope of this or not but I thought id post it here see what you guys think

You can already pull up a user (`getAuthor`) and check their identities field for Discord. However, we're waiting on #38 to be merged and deployed as that feature has been having some issues. We're hoping #38 will fix it for good.
