### ISSUE TITLE
Cannot find author 'md_5'

### ISSUE THREAD

**Issue by md-5** [SpigotMC/XenforoResourceManagerAPI#41]
?action=findAuthor&name=md_5 --> "Invalid name. Name must be alphanumeric."

**Comment by simpleauthority** [comment]
Amazing. I thought names were alnum and completely forgot your name with an underscore in it. 🤦‍♂️

**Comment by md-5** [comment]
^[A-Za-z0-9_.-]{3,16}$
New signups must match this, but we do have legacy usernames which have spaces and are longer than 16 chars.

**Comment by simpleauthority** [comment]
Was there an upper limit on the legacy username length before the 16 char limit was introduced? Trying to get regex as tight as possible. For now will just do minimum 3 chars and no length ceiling. Let me know though.
