### ISSUE TITLE
Minecraft Versions are displaying weirdly

### ISSUE THREAD

**Issue by md-5** [SpigotMC/XenforoResourceManagerAPI#42]
```
"native_minecraft_version":"1._13","supported_minecraft_versions":["1._13"]
```

Note the .

**Comment by simpleauthority** [comment]
Woops. Environment difference. I'll fix it.

**Comment by md-5** [comment]
Our fields are configured with values: 'legacy', '1_13', '1_14', etc and text: 'Legacy (< 1.13)', '1.13', '1.14' etc.
