### ISSUE TITLE
Wrong default icon

### ISSUE THREAD

**Issue by itaquito** [SpigotMC/XenforoResourceManagerAPI#52]
Hey! When you try to get the icon of a resource that doesn't have one, you get the link of the default one. Everything good on that, except that is showing the wrong default icon...

This is the default icon the API shows: https://www.spigotmc.org/styles/default/xenresource/resource_icon.png
But this is the one Spigot uses: https://static.spigotmc.org/styles/spigot/xenresource/resource_icon.png (or https://www.spigotmc.org/styles/spigot/xenresource/resource_icon.png) I'm not sure which URL you should use, probably the first one. For sure md_5 knows.

Thanks again.

**Comment by md-5** [comment]
Yup.

Should probably add a PUBLIC_PATH_STATIC or something for the default avatar too

**Comment by simpleauthority** [comment]
Good catch! Will submit a patch soon.
