### ISSUE TITLE
Premium Verifier

### ISSUE THREAD

**Issue by Lorenzo0111** [SpigotMC/XenforoResourceManagerAPI#56]
It may be very useful a way to check if a premium resource DownloadID is valid

**Comment by simpleauthority** [comment]
Can you elaborate on what this means please?

**Comment by Lorenzo0111** [comment]
Something like an endpoint to verify if a downloadid("%%__NONCE__%%" premium placeholder) is valid or to check if someone bought the plugin

**Comment by simpleauthority** [comment]
This is already planned in #8, which is pending API keys to be made which is out of control of this project. But one day, we do want to have this
