### ISSUE TITLE
Get information to members (getMemberById)

### ISSUE THREAD

**Issue by YellowPhoenix18** [SpigotMC/XenforoResourceManagerAPI#57]
In some cases a verification of the spigot profile is needed. It would be helpful, if the API offers a endpoint to get the username and current Status of a member. This could help to create a bot checking if the user set a specific key as his/her status to verify this user is legit. This would over time also reduce the massive leaking of spigot premium-ressources, as developers can limit support for people using illegal copies.

Example GET index.php?action=getMemberById&id=41621:

```
{
  "id": "41621",
  "username": "SourceWriters",
  "currentStatus": "Working on RWG v5",
   "etc": "..."
}
```

**Comment by simpleauthority** [comment]
Is there any reason why `getAuthor` or `findAuthor` do not work?

https://api.spigotmc.org/simple/0.2/index.php?action=getAuthor&id=41621
https://api.spigotmc.org/simple/0.2/index.php?action=findAuthor&name=SourceWriters
```json
{
  "id": "41621",
  "username": "SourceWriters",
  "resource_count": "36",
  "identities": {
    "skype": "yellowphoenix18",
    "twitter": "syntaxphoenix"
  },
  "avatar": "https://www.spigotmc.org/data/avatars/l/41/41621.jpg?1612979380"
}
```

**Comment by YellowPhoenix18** [comment]
Thank you for the fast reply. Youre right. Basically getAuthor would work. I first thought this method was just for authors related to resources. But may you could add a option to get the status-messages the user has posted over time or at least the latest status? As mentioned that would make many things very easy

**Comment by md-5** [comment]
No, status messages as verification is not something we want to encourage. It just pollutes the site.
There is the Discord identities for a reason.

**Comment by simpleauthority** [comment]
Yeah, as md said I don't think statuses, posts, profile comments, etc are good additions to this API. This API is purely information gathering, specially regarding the resource manager but some limited info about users themselves as well.

Identities are good for what you want to do here.

Thanks for the suggestion, though!

**Comment by YellowPhoenix18** [comment]
That makes sense, its also a good starting-point to build an api on. Then this request can basically get closed

**Comment by YellowPhoenix18** [comment]
Sorry for reopening that issue here, but I was rethinking about the identifiers. Basically they are a good idea, but at some spot I think they limit the users.
I agree with the point, that using the status is a bad idea and would end up in spam.

But for the case, that users have no Discord(e.g. China) a verification will get hard.

My own plan was to create some web-dashboards to handle license-management. But using the discord-identifier would limit the application to beeing in the need, that users have discord. Using the identifiers with own verification-ids would probably ending up in me getting banned so here is my request I have:

May there should be a new identifier, which can be used by developers for verification of the users to also create applications aside from the users beeing in the need to have discord or other apps. This would fix all issues and is in my opinion also not really spammy

**Comment by simpleauthority** [comment]
So, the idea here is that generally this API is not for verifying people. It is simply a common use that people are using the identities capability for. The API was not designed to act as a DRM intermediary. I don't think @md-5 wants it to be, either, but he can speak to that.

Later, when API keys for viewing who has purchased your plugin or what plugins you have purchased, you could do your web-dashboard idea. But, as mentioned in the other issue that is pending the ability for somebody to make an XF plugin, other reputable devs to audit it, and then having it released and deployed before we can ever bring that functionality into _this_ project.

Thank you for your ideas! I just don't think they fit this project's intention (which is to read data out only.)
