### ISSUE TITLE
Lower the cache TTL for author-related endpoints

### ISSUE THREAD

**Issue by lus** [SpigotMC/XenforoResourceManagerAPI#59]
Currently the API seems to be cached by Cloudflare which may lead to unexpected behaviour when awaiting some specific result.
I suggest disabling the Cloudflare cache for the `api.spigotmc.org` subdomain using a page rule.

**Comment by md-5** [comment]
No, max age is 6 hours: https://github.com/SpigotMC/XenforoResourceManagerAPI/blob/master/src/API.php#L18

**Comment by lus** [comment]
Oh, well, I see. I just read `max_age: 604800` but did not pay attention on what particular header it was lol.
6 hours seems reasonable, at least for resource information I'd say. As long as there is no other way to reliably verify Spigot user accounts I'd suggest lowering the TTL to around 10-30 minutes specifically for the `getAuthor` and `findAuthor` endpoints to find a good balance between resource saving and user experience for 3rd party apps (so that their users don't need to wait 6 hours after filling in their information).

**Comment by simpleauthority** [comment]
If this is still relevant please reopen.
