### ISSUE TITLE
`listResources` endpoint category parameter issues

### ISSUE THREAD

**Issue by Phoenix616** [SpigotMC/XenforoResourceManagerAPI#60]
There are currently two issues with the `listResources` endpoint:

1. The readme [states](https://github.com/SpigotMC/XenforoResourceManagerAPI#parameters) that the parameter is `cat` while it [actually uses `category`](https://github.com/SpigotMC/XenforoResourceManagerAPI/blob/3ca9932aff7db322f051f2ccfec62289e2aad705/src/util/RequestUtil.php#L76). (Passing `cat` will just lead to it showing all resources)
2. Trying to use the `category` parameter instead will just lead to the response `{"code":404,"message":"Nothing was found for that request."}` no matter the category ID. ([example with ID 4 (Spigot)](https://api.spigotmc.org/simple/0.2/index.php?action=listResources&category=4))

**Comment by simpleauthority** [comment]
Can confirm, weird. I'll look as soon as I can, no time at the moment

**Comment by md-5** [comment]
> Trying to use the category parameter instead will just lead to the response {"code":404,"message":"Nothing was found for that request."} no matter the category ID. (example with ID 4 (Spigot))

This has been fixed

**Comment by simpleauthority** [comment]
Oh ok. Sounds good
