### ISSUE TITLE
The paginated pages in the api are in reverse order to spigot pages 

### ISSUE THREAD

**Issue by MrButtersDEV** [SpigotMC/XenforoResourceManagerAPI#63]
Ok, so my resource AutoPivkup has 5 pages of updates. On spigot page "1" it contains the most recent updates and page "5" has the oldest updates for the plugin. When using `&page=1` I get the 5th and oldest page of updates on spigot and when I use `&page=5` I get the latest updates. The use of 1 `&page=#` should be changed to match the content on the same page as if you were viewing it on spigot. 

https://api.spigotmc.org/simple/0.2/index.php?action=getResourceUpdates&id=70157&page=5
https://www.spigotmc.org/resources/autopickup-1-18-support.70157/updates?page=5

**Comment by simpleauthority** [comment]
Fair point.

**Comment by Pangamma** [comment]
Otherwise you have to use the number of updates and the expected page size (10) to determine which page to grab. And that's shaky logic.

**Comment by simpleauthority** [comment]
I am going to be adding pagination information to any paginated response. However, to change the default ordering would be a breaking change and would need a version bump. I will probably instead add a sort argument, but the default will remain as is.
