### ISSUE TITLE
API returning wrong resurces?

### ISSUE THREAD

**Issue by TheSilentPro** [SpigotMC/XenforoResourceManagerAPI#65]
Using action `listResources`
Fetching category id 25 (i assume this is category id for SKRIPT) page 1: 
first result is `MineRewards` which when looked into spigot is supposed to be Tools And Utilities.
the second page returns `Lucky Block - Vers. Español` which is actually in the skript category.
Whats going on here?

Also: Is there a list of category ids and their respective name on the spigot page?

**Comment by simpleauthority** [comment]
When I access `https://api.spigotmc.org/simple/0.2/index.php?action=listResources&category=25`

I see `MineRewards` as you state, with resource ID `3992`. 

When accessing `https://www.spigotmc.org/resources/minerewards.3992/` for that resource, I see it is categorized under `Skript` as expected.

Why do you think it should be in `Tools and Utilities`?

`https://www.spigotmc.org/resources/lucky-block-vers-espa%C3%B1ol.6013/` as you state is also in the correct category.

And also yes there is already a category ID to name mapping found in the documentation: https://api.spigotmc.org/simple/0.2/index.php?action=listResourceCategories

**Comment by TheSilentPro** [comment]
> When I access `https://api.spigotmc.org/simple/0.2/index.php?action=listResources&category=25`
> 
> I see `MineRewards` as you state, with resource ID `3992`.
> 
> When accessing `https://www.spigotmc.org/resources/minerewards.3992/` for that resource, I see it is categorized under `Skript` as expected.
> 
> Why do you think it should be in `Tools and Utilities`?
> 
> `https://www.spigotmc.org/resources/lucky-block-vers-espa%C3%B1ol.6013/` as you state is also in the correct category.

Oh my mistake i was looking at the wrong resource.


> 
> And also yes there is already a category ID to name mapping found in the documentation: https://api.spigotmc.org/simple/0.2/index.php?action=listResourceCategories
But those have "duplicate" categories, for example Transportation (id:5) and Transporation (id:10) is the same name
I'm assuming one is normal spigot transportation and the other one is bungee-transportation, but there is no distinction between them as far as i can see?

**Comment by TheSilentPro** [comment]
Noticed that the URL when viewing a category also says the id of the category, I matched them like that
Would be nice to have the `listResourceCategories` return a description with information like that or something similar.
_Some categories do have this description, but others do not._

**Comment by simpleauthority** [comment]
Unfortunately, this is how we get the IDs of everything. We check the Spigot site and look at the URL. The ID is usually at the end preceded by a dot. `listResourceCategories` already has the description if it is there, so not sure what you want to be added. The "duplicated" categories as mentioned above are not really duplicated. They are simply children of different parent categories (i.e. Spigot/Bungee.) Generally we assume that when using this API you know the ID you want already (by checking the URL.)

I'm closing this because I think the API is fine as is, however if you disagree you can reopen this or make a new issue. Thanks!
